site_name: kmua の小站
site_author: Krau
site_description: 关于 kmua 已知的情报
repo_name: krau/kmua-bot
repo_url: https://github.com/krau/kmua-bot
copyright: CC BY-NC-SA 4.0
theme:
  name: material
  language: zh
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: 亮色模式



plugins:
  - optimize

nav:
  - index.md
  - help.md
  - self-host.md
  - license.md
